### ISSUE TITLE
Custom bar color

### ISSUE THREAD

**Issue by liurui39660** [jonathanlermitage/intellij-night-and-day-plugin#1]
An interesting plugin. Just hope if I can customize the color of the bar. Currently, the green color is very close to my background image.

**Comment by jonathanlermitage** [comment]
Hi!  
Yes, I totally agree. This first release is a bit basic, but I have some plans to make it more configurable. I will create milestones soon.

**Comment by jonathanlermitage** [comment]
Done in 1.1 release. Published today to JB portal, should be available to download next week.
